### ISSUE TITLE
demo中农历显示不对

### ISSUE THREAD

**Issue by zhaojizhou** [jinliming2/Calendar-js#1]
您好！
这是个非常好的工具，很赞！！！
但我从浏览器打开demo后，发现：
1.农历顺序是倒的；
2.每年正月初一有显示undefined的内容；
3.刚打开demo时月份没有显示，要选一下才有，可能元素宽度不够。
再次感谢您提供的工具！

**Comment by jinliming2** [comment]
您好，感谢您的反馈。
前两个错误是由于在重构的时候粗心：
第一个是将参数写反了，导致顺序倒过来了；
第二个是正月初一返回的数据格式写错了，与其他不一样，所以读不到指定的字段，就 undefined 了。

第三个错误是由于现在是 1 月份导致的：因为程序在初始化时会创建一个 Date 对象，初始化时间戳为 0，也就是 1970 年 1 月 1 日 0 点 0 分 0 秒，而由于现在是 1 月份，日期与初始化的日期相同，所以在设置日期的时候就跳过了月份的设置，所以导致月份在初始化后不显示。
